# Generated by Django 4.0 on 2023-11-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basic_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, null=True)),
                ('gender', models.TextField(max_length=10, null=True)),
                ('juusyo', models.CharField(max_length=200, null=True)),
                ('moyori', models.CharField(max_length=200, null=True)),
                ('gakureki', models.CharField(max_length=200, null=True)),
                ('sikaku1', models.CharField(max_length=200, null=True)),
                ('sikaku2', models.CharField(max_length=200, null=True)),
                ('sikaku3', models.CharField(max_length=200, null=True)),
                ('like', models.CharField(max_length=200, null=True)),
                ('year1', models.CharField(max_length=8, null=True)),
                ('month1', models.CharField(max_length=8, null=True)),
                ('input1', models.CharField(max_length=200, null=True)),
                ('year2', models.CharField(max_length=8, null=True)),
                ('month2', models.CharField(max_length=8, null=True)),
                ('input2', models.CharField(max_length=200, null=True)),
                ('year3', models.CharField(max_length=8, null=True)),
                ('month3', models.CharField(max_length=8, null=True)),
                ('input3', models.CharField(max_length=200, null=True)),
                ('year4', models.CharField(max_length=8, null=True)),
                ('month4', models.CharField(max_length=8, null=True)),
                ('input4', models.CharField(max_length=200, null=True)),
                ('year5', models.CharField(max_length=8, null=True)),
                ('month5', models.CharField(max_length=8, null=True)),
                ('input5', models.CharField(max_length=200, null=True)),
                ('year6', models.CharField(max_length=8, null=True)),
                ('month6', models.CharField(max_length=8, null=True)),
                ('input6', models.CharField(max_length=200, null=True)),
                ('year7', models.CharField(max_length=8, null=True)),
                ('month7', models.CharField(max_length=8, null=True)),
                ('input7', models.CharField(max_length=200, null=True)),
                ('year8', models.CharField(max_length=8, null=True)),
                ('month8', models.CharField(max_length=8, null=True)),
                ('input8', models.CharField(max_length=200, null=True)),
                ('year9', models.CharField(max_length=8, null=True)),
                ('month9', models.CharField(max_length=8, null=True)),
                ('input9', models.CharField(max_length=200, null=True)),
                ('input10', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
